# Generated by Django 6.0.2 on 2026-02-19 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoJuego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('annio', models.PositiveBigIntegerField()),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videojuego', to='catalogo.genero')),
                ('plataforma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='videojuego', to='catalogo.plataforma')),
            ],
        ),
        migrations.DeleteModel(
            name='VideoJuegos',
        ),
    ]
