# Generated by Django 6.0.2 on 2026-02-25 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'permissions': [('ver_articulo_vip', 'Puede ver artículo VIP')]},
        ),
    ]
